### PR TITLE
Do not try to access highlighted attributes without checking if they exist

### PR DESCRIPTION
**Pull request by redox**
The JS code was accessing an undefined `excerpt` attribute (`excerpt` is not highlighted, because I didn't include it in the `attributesToIndex` list):

``` json
{
  "attributesToIndex":["title","unordered(content)"],
  "customRanking":["desc(modified)"]
} 
```

### CODE REVIEW

**Comment by redox** [comment]
Thanks to your work, it's now live on http://blog.algolia.com :+1:

**Comment by mustela** [comment]
Thanks @redox! Looking forward to see that post ;)

**Comment by mustela** [comment]
@redox it's live now http://wordpress.org/plugins/maven-algolia/, in case you want to update yours. ;)

**Comment by redox** [comment]
Great, I'll update our plugin to the released version in the next few days! :+1:

**Pull request merged**
